export const authTypes = {
	SIGN_UP: 'SIGN_UP',
	LOG_IN: 'LOG_IN',
	LOG_OUT: 'LOG_OUT',
	GET_USER: 'GET_USER',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	AUTH_LOADING: 'AUTH_LOADING'
};

export const userTypes = {
	GET_USER_PROFILE: 'GET_USER_PROFILE',
	CLEAR_CURRENT_PROFILE: 'CLEAR_CURRENT_PROFILE',
	USER_LOADING: 'USER_LOADING'
};
